### ISSUE TITLE
Accent colors overwriting in-app colors

### ISSUE THREAD

**Issue by JakeChambersOy** [EcrosoftXiao/device_xiaomi_cepheus#1]
Spotify now playing screen is taking its background color from the accent color(s). 

It normally should take the color dynamically from the album art.

According to the RROS telegram channel this is due to selinux permissive, although it's already set to enforced on the mi9.

**Comment by EcrosoftXiao** [comment]
Thanks for you hint. Heve blocked Spotify from reading theme prop.
Can you help me test [this build](https://mega.nz/file/HQYhRaab#StNEeoGFlcHuruV9sf4UeVETtE2k-Unj4PFFrDiQ_CE) to see if it works?

**Comment by EcrosoftXiao** [comment]
Thanks for you hint. Heve blocked Spotify from reading theme prop.
Can you help me test [this build](https://mega.nz/file/HQYhRaab#StNEeoGFlcHuruV9sf4UeVETtE2k-Unj4PFFrDiQ_CE) to see if it works?

**Comment by JakeChambersOy** [comment]
Thank you for your quick reply!
I will test it as soon as possible (at work right now).
Another user told be that there are also elements which get themed by the accent colors in YouTube (Vanced) and Instagram.

**Comment by EcrosoftXiao** [comment]
> Thank you for your quick reply!
> I will test it as soon as possible (at work right now).
> Another user told me that there are also elements which get themed by the accent colors in YouTube (Vanced) and Instagram.
> 
> Edit:
> You've linked to the .md5sum file, not the full zip.

Ah sry. Edited.

**Comment by JakeChambersOy** [comment]
Spotify is back to normal on the new build. 
Thanks for your quick support! 

I will let you know about the other apps once I get feedback from my friend.

**Comment by EcrosoftXiao** [comment]
> Spotify is back to normal on the new build.
> Thanks for your quick support!
> 
> I will let you know about the other apps once I get feedback from my friend.

Np bro, thanks for your feedback.

**Comment by WolfyG97** [comment]
> 
> 
> Thanks for your hint. Heve blocked Spotify from reading theme prop.
> Can you help me test [this build](https://mega.nz/file/zNBlxCpA#kst1eZ21EIY7V0QKiQc0A2CzE1V3-7Vr-_glv0OkRLQ) to see if it works?

Did you also block instagram and youtube?
On instagram right before you view the story of a "close friend" the ring around the profile photo uses the accent color
On youtube (vanced) the whole story preview is tinted with the accent color
Also is there any other way to get news about this rom? If not it would be nice to post changelongs and instructions of as to dirty flash or clean flash new updates.
Thanks for the rom really enjoying it!

**Comment by JakeChambersOy** [comment]
I think this issue is fixed now. I didn't encounter any other instances where accent colors are interfering with third-party-apps.
