### ISSUE TITLE
Google assistance doen't wake up under screen-off state when said " OK, google"

### ISSUE THREAD

**Issue by krischen62** [EcrosoftXiao/device_xiaomi_cepheus#2]
As the title, would you kindly fix that in next coming build ?

**Comment by EcrosoftXiao** [comment]
> As the title, would you kindly fix that in next coming build ?

Can you help me check this version?
Gapps version: https://mega.nz/file/yJIE0BRK#De2VEcEBa4Gom3_1wA--Ly6izTNv1wqFgriMV0ZOtaA
md5 checksum:https://mega.nz/file/fRYEEDqI#kIL6Oy6C1xXRK2Mt-GSTjZs4Q5vY2SHnykDDrKIc1Os

**Comment by krischen62** [comment]
At first, I want to say thank you that you put your effort on this legend rom and it works perfectly !
After testing this new version, it works !  
Now I can say " OK google" to wake up my phone and use google assistant.

**Comment by JakeChambersOy** [comment]
> > As the title, would you kindly fix that in next coming build ?
> 
> Can you help me check this version?
> Gapps version: https://mega.nz/file/yJIE0BRK#De2VEcEBa4Gom3_1wA--Ly6izTNv1wqFgriMV0ZOtaA
> md5 checksum:https://mega.nz/file/fRYEEDqI#kIL6Oy6C1xXRK2Mt-GSTjZs4Q5vY2SHnykDDrKIc1Os

I can confirm it works as intended now. Very much thanks for that! 
What I noticed though, is that the "hotword listened" and "command listened" sounds are missing now, no matter how I toggle the assistant.
