### ISSUE TITLE
Some problem with bluetooth audio  

### ISSUE THREAD

**Issue by yuky2020** [EcrosoftXiao/device_xiaomi_cepheus#3]
On last build bluetooth audio dosen't work well ,device will pair ,but then the audio is super laggy , same problem on derpfest and with quantic kernel ; 
no problem on other rom ; 
the problem is not on every hearphone midots (work well )
# thanks,for your time

**Comment by EcrosoftXiao** [comment]
> On last build bluetooth audio dosen't work well ,device will pair ,but then the audio is super laggy , same problem on derpfest and with quantic kernel ;
> no problem on other rom ;
> the problem is not on every hearphone midots (work well )
> 
> # thanks,for your time

Bt audio works here perfectly. It would helpful if you can share me a logcat.

**Comment by yuky2020** [comment]
``---- 2 nov 2020 10:47:48 ----

11-02 10:47:48.450  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 10:50:34.244  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 10:52:35.384  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 10:53:46.537  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 10:53:46.552  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:11:18.629  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:11:18.703  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:11:43.232  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:11:43.239  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:11:48.584  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:12:44.931  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:12:44.955  1962  2772 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:12:45.537  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:12:45.539  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:12:45.541  1962  1962 W Avrcp_ext: getMediaPlayerInfo: com.android.bluetooth not found

11-02 11:12:45.548  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:12:45.557  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:12:45.561  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:12:45.562  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 2 lines

11-02 11:12:45.562  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 1 line

11-02 11:12:45.599  1962  1962 I chatty  : uid=1002(bluetooth) com.android.bluetooth identical 3 lines

11-02 11:12:45.638  1962  2133 E BluetoothHeadsetServiceJni: 	at com.android.bluetooth.hfp.HeadsetService.messageFromNative(HeadsetService.java:421)

11-02 11:12:45.638  1962  2133 E BluetoothHeadsetServiceJni: 	at com.android.bluetooth.hfp.HeadsetNativeInterface.sendMessageToService(HeadsetNativeInterface.java:62)

11-02 11:12:45.638  1962  2133 E BluetoothHeadsetServiceJni: 	at com.android.bluetooth.hfp.HeadsetNativeInterface.onConnectionStateChanged(HeadsetNativeInterface.java:78)

11-02 11:12:46.192  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:13:16.259  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:13:50.704  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

11-02 11:14:20.747  1407  1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}

---- 2 nov 2020 11:15:39 ----

**Comment by EcrosoftXiao** [comment]
> ``---- 2 nov 2020 10:47:48 ----
> 
> 11-02 10:47:48.450 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 10:50:34.244 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 10:52:35.384 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 10:53:46.537 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 10:53:46.552 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:11:18.629 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:11:18.703 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:11:43.232 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:11:43.239 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:11:48.584 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:12:44.931 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:12:44.955 1962 2772 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:12:45.537 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:12:45.539 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:12:45.541 1962 1962 W Avrcp_ext: getMediaPlayerInfo: com.android.bluetooth not found
> 
> 11-02 11:12:45.548 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:12:45.557 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:12:45.561 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:12:45.562 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 2 lines
> 
> 11-02 11:12:45.562 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 1 line
> 
> 11-02 11:12:45.599 1962 1962 I chatty : uid=1002(bluetooth) com.android.bluetooth identical 3 lines
> 
> 11-02 11:12:45.638 1962 2133 E BluetoothHeadsetServiceJni: at com.android.bluetooth.hfp.HeadsetService.messageFromNative(HeadsetService.java:421)
> 
> 11-02 11:12:45.638 1962 2133 E BluetoothHeadsetServiceJni: at com.android.bluetooth.hfp.HeadsetNativeInterface.sendMessageToService(HeadsetNativeInterface.java:62)
> 
> 11-02 11:12:45.638 1962 2133 E BluetoothHeadsetServiceJni: at com.android.bluetooth.hfp.HeadsetNativeInterface.onConnectionStateChanged(HeadsetNativeInterface.java:78)
> 
> 11-02 11:12:46.192 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:13:16.259 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:13:50.704 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> 11-02 11:14:20.747 1407 1438 W BroadcastQueue: Association not allowed: broadcasting Intent { act=android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED flg=0x1000010 (has extras) } from com.android.bluetooth (pid=1962, uid=1002) to com.google.android.as through BroadcastFilter{f8c49a6 10219/u0 ReceiverList{3621701 3163 com.google.android.as/10219/u0 remote:b01a4e8}}
> 
> ---- 2 nov 2020 11:15:39 ----

Can you give me a full log? I can't get any information form what you show me.

**Comment by yuky2020** [comment]
After a clean install of last version ( the one on the other issue )
I can't replicate the problem so i think is fixed
